# Generated by Django 5.1.2 on 2024-12-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="category",
            field=models.CharField(
                choices=[
                    ("hotel", "Hotel"),
                    ("restaurant", "Restaurant"),
                    ("event", "Event"),
                ],
                max_length=50,
            ),
        ),
    ]
