# Generated by Django 5.1.2 on 2024-10-29 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_traveller_email_traveller_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chosenactivity",
            name="user",
        ),
        migrations.RemoveField(
            model_name="calendar",
            name="user",
        ),
        migrations.DeleteModel(
            name="Traveller",
        ),
    ]
