# Generated by Django 5.1.2 on 2024-11-19 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_calendar_user_chosenactivity_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chosenactivity",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.activity"
            ),
        ),
        migrations.AlterField(
            model_name="chosenactivity",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="chosenactivity",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="chosenactivity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
