# Generated by Django 5.1.2 on 2024-11-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_chosenactivity_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chosenactivity",
            name="end_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="chosenactivity",
            name="start_date",
            field=models.DateTimeField(null=True),
        ),
    ]
