# Generated by Django 5.1.2 on 2024-11-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_chosenactivity_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chosenactivity",
            name="endTimeZone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="chosenactivity",
            name="startTimeZone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
