# Generated by Django 5.1.2 on 2024-11-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_chosenactivity_endtimezone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="chosenactivity",
            name="color",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="chosenactivity",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chosenactivity",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="chosenactivity",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
