# Generated by Django 5.1.2 on 2024-11-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_activity_address_activity_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="calendar",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
