# Generated by Django 5.1.2 on 2024-12-02 03:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_calendar_end_date_calendar_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2024, 12, 2, 3, 17, 41, 322616),
            ),
            preserve_default=False,
        ),
    ]
