# Generated by Django 5.1.2 on 2024-12-03 03:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_post"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="post_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
