# Generated by Django 5.1.2 on 2024-12-04 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_friend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chosenactivity",
            name="calendar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.calendar",
            ),
        ),
    ]
